modLoader="javafml" #mandatory

loaderVersion="[2,]" #mandatory

license="MIT"

issueTrackerURL="" #optional

[[mods]] #mandatory
modId="letsgogambling"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/DayTheMagpie/Let-s-Go-Gambling-"
logoFile = "icon.png"
mod_authors="${mod_authors}" #optional
description='''A decorative mod... for now.

Credits:
DayTheMagpie - Art and Code
wdiscute - Being my braincell while I learned how to code
'''

[[dependencies.letsgogambling]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="${neo_version_range}" #mandatory
ordering="AFTER"
side="BOTH"

# Here's another dependency
[[dependencies.letsgogambling]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.letsgogambling]]
modId="fusion"
type="optional"
versionRange="[1.0.0,)"
ordering="NONE"
side="CLIENT"